voxpupuli/puppet-redis

manifests/params.pp
manifests/sentinel.pp
spec/classes/redis_sentinel_spec.rb
templates/redis-sentinel.conf.erb

Added auth-pass to redis sentinel
Updated test for redid-sentinel (auth_pass)

Sentinel auth pass

---

manifests/config.pp
manifests/sentinel.pp
templates/redis-sentinel.conf.erb
templates/redis.conf.erb

copy variables used in template to local scope

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
templates/redis.conf.erb

I added save_db_to_disk parameter.

Save db to disk

---

metadata.json

Bump puppetlabs-stdlib version spec

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/redis_spec.rb
templates/redis.conf.erb

Redis support hz option to improve performance of the background tasks.

add support for hz option

---

spec/classes/redis_spec.rb

Adds spec for unixsocket and perms

---

manifests/params.pp
spec/classes/redis_freebsd_spec.rb
spec/spec_helper.rb

FreeBSD fixes

---

.travis.yml
Gemfile
Rakefile
manifests/config.pp
manifests/init.pp
manifests/preinstall.pp

Consolidate Travis and testing boilerplate
* Mainly from voxpupuli’s module sync
* Simplified Travis Matrix
* Updated Rakefile with options
Fixes puppet-lint issues
manifests/config.pp - FIXED: missing trailing comma after last element on line 74
manifests/init.pp - FIXED: class included by relative name on line 599
manifests/init.pp - FIXED: class included by relative name on line 600
manifests/init.pp - FIXED: class included by relative name on line 601
manifests/init.pp - FIXED: class included by relative name on line 602
manifests/preinstall.pp - FIXED: class included by relative name on line 58
manifests/preinstall.pp - FIXED: class included by relative name on line 73

Consolidate travis and testing

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/redis_spec.rb
templates/redis.conf.erb

Rebase of #112, squashed and added spec

Add save interval squash

---

.travis.yml

Add fast finish to Travis

---

manifests/preinstall.pp
metadata.json

* Update apt module for new changes
Closes https://github.com/arioch/puppet-redis/pull/100

Fixes gpg key for DotDeb

---

.travis.yml

* Also add Beaker docker jobs for acceptance testing Redis more now we’ve slimmed down the unit tests

Speed up Travis even more

---

manifests/preinstall.pp

* powerstack.org no longer exists
* Redis is now in EPEL
Closes #103

Move Repo for RHEL systems to EPEL

---

.gitignore
.rspec
Gemfile
spec/classes/redis_spec.rb
spec/spec_helper.rb

Extracting the unit test refactoring from #132

Refactor unit tests

---

manifests/config.pp
spec/classes/redis_spec.rb

adding /var/run/redis for Debian based hosts

---

manifests/config.pp
manifests/init.pp
manifests/params.pp

Manage workdir and permissions

---

spec/classes/redis_spec.rb
templates/redis.conf.erb

Rebase of https://github.com/arioch/puppet-redis/pull/139

For folks that do not use redis to cache to disk

---

manifests/params.pp

* Defaults to version of package available in upstream package manager
* Will be used to check parameter later

Adds minimum versions parameters

---

manifests/params.pp

This commit adds the needed params for Archlinux.

Added Archlinux as supported OS

---

manifests/params.pp
metadata.json
spec/spec_helper.rb

This commit adds tests for Archlinux.
While testing found an issue with the 'config_dir' parameter.
Signed-off-by: bjanssens <bjanssens@inuits.eu>

Archlinux: Added tests and update config_dir parameter

---

README.md

README lint

---

manifests/init.pp

* New style guide rule: 
https://docs.puppet.com/puppet/latest/style_guide.html#chaining-arrow-syntax

Fixes lint arrow errors

---

spec/acceptance/nodesets/multi-node-master-slave.yml
spec/acceptance/redis_multi_node_spec.rb

First iteration for eventual seninel testing from #166

Adds acceptance test for master/slave testing

---

manifests/config.pp
manifests/init.pp

* Slight refactoring and DRY-ing up of code
* No logic changes

Refactoring common code patterns

---

manifests/init.pp
manifests/preinstall.pp
manifests/sentinel.pp

* Explicitly set packages after apt install

Fixes ordering of Apt repos

---

spec/acceptance/redisget_spec.rb

Adds acceptance tests for the redisget() function

---

metadata.json

Updates metadata supported versions

---

manifests/config.pp

* This is done at a class level in init.pp
* Do not need to specify individual service

Remove service notification

---

lib/puppet/parser/functions/getvar_emptystring.rb
lib/puppet/parser/functions/redisget.rb

* redisget() doc update
* getvar_emptystring() doc update

Updates docs for puppet functions

---

.travis.yml

As suggested in #185.
Why not bite the bullet and just try. 😄

Make TravisCI push to the Forge

---

Gemfile
Rakefile
manifests/init.pp

Update manifest docs for puppet-strings
* Allows automatic generation of docs
* Adds rake task for doc generation

Update docs for puppet-strings

---

spec/acceptance/nodesets/centos-6-docker.yml
spec/acceptance/nodesets/centos-7-docker.yml

* New images doesn't have the locale issues

Updates docker images for CentOS 6 and 7

---

templates/service_templates/redis.service.erb

made some small updates to the systemd service unit file to better handle multiple instances.

updated redis systemd unit file for better use with instances

---

manifests/init.pp
spec/acceptance/redis_multi_node_spec.rb
spec/classes/redis_spec.rb

Allow `slaveof` when binding to localhost

---

.msync.yml
.travis.yml
Gemfile
Rakefile

modulesync 2.7.0

---

manifests/init.pp
manifests/instance.pp
spec/classes/redis_spec.rb
templates/redis.conf.2.4.10.erb
templates/redis.conf.2.8.erb
templates/redis.conf.3.2.erb
templates/redis.conf.erb

Fixing repl_ping_slave_period not being managed inside template.

Fixing repl_ping_slave_period not being managed with params

---

manifests/params.pp

Fixes a spelling mistake where "give" should've been used instead of "git."
None

Spelling fix

---

CHANGELOG.md
REFERENCE.md
metadata.json

release 4.2.1

---

.msync.yml
.travis.yml
Gemfile
Rakefile

modulesync 2.10.0

---

.sync.yml
.travis.yml
manifests/params.pp
metadata.json
spec/classes/redis_sentinel_spec.rb

Add Debian 10 support

---

.sync.yml
.travis.yml
metadata.json
spec/acceptance/suites/scl/redis5_spec.rb
spec/classes/redis_spec.rb

Add support for RedHat/CentOS 8

Add support for RedHat/CentOS 8

---

.github/CONTRIBUTING.md
.msync.yml
.rubocop.yml
Gemfile
Rakefile
spec/classes/redis_spec.rb
spec/spec_helper.rb

modulesync 2.12.0

---

spec/classes/redis_spec.rb
templates/service_templates/redis.service.erb

change systemd stop command to redis-cli

---

.sync.yml
.travis.yml
manifests/params.pp
metadata.json

Add Ubuntu 20.04 support

---

.github/SECURITY.md
.msync.yml
.rubocop.yml
.travis.yml
Gemfile
manifests/administration.pp
manifests/config.pp
manifests/globals.pp
manifests/init.pp
manifests/install.pp
manifests/instance.pp
manifests/params.pp
manifests/preinstall.pp
manifests/sentinel.pp
manifests/service.pp
spec/acceptance/redis_cli_task_spec.rb
spec/spec_helper_acceptance.rb

modulesync 3.0.0 & puppet-lint updates

---

REFERENCE.md
lib/puppet/functions/redis/get.rb
manifests/administration.pp
spec/acceptance/suites/default/redis_adminstration_spec.rb
spec/classes/redis_administration_spec.rb

After discussing #384 with @ekohl  I have reached the conclusion that instead of further complicating this module, it would be best to simplify it and recommend the forge module for disabling THP.
I greatly appreciate all the feedback.
Closes #372

Remove support for THP in Redis module - recommend forge module

---

manifests/params.pp

Solves issue https://github.com/voxpupuli/puppet-redis/issues/341
Pull Request (PR) description
This Pull Request (PR) fixes the following issues

Correct config_dir for scl support

---

CHANGELOG.md
Gemfile
metadata.json

Release 8.0.0

---

manifests/init.pp
manifests/instance.pp
spec/classes/redis_spec.rb
templates/redis.conf.epp

Allows you to disable Slow log by setting slowlog_log_slower_than to -1
Reference [here](https://redis.io/commands/slowlog#redis-slow-log-overview).
Fixes #404

Allow disable to disable slow log

---

CHANGELOG.md
REFERENCE.md
metadata.json

Release 8.1.1

---

manifests/init.pp
manifests/instance.pp
spec/classes/redis_spec.rb
templates/redis.conf.epp

We want to manage loadmodule directives to allow someone to manage additional redis modules.

manage additional redis modules

---

manifests/init.pp
manifests/instance.pp

Allow conditional restarts of a redis instance on configuration changes.

conditional instance restarts on config file changes

---

metadata.json
spec/classes/redis_spec.rb
templates/service_templates/redis.service.epp

Right now this is untested. I'll have to see what CI says.

Add Debian 11 support

---

manifests/dnfmodule.pp
manifests/globals.pp
manifests/init.pp
manifests/install.pp
metadata.json
spec/acceptance/suites/dnfmodule/redis_spec.rb
spec/classes/redis_spec.rb

Add support for managing Redis dnfmodule on EL 8+

---

CHANGELOG.md
REFERENCE.md
metadata.json

Release 8.6.0

---

CHANGELOG.md
REFERENCE.md
metadata.json

Release 8.7.0

---

manifests/init.pp
manifests/instance.pp
spec/classes/redis_spec.rb
templates/redis.conf.epp

This PR is based on https://github.com/voxpupuli/puppet-redis/pull/449 (Fixes https://github.com/voxpupuli/puppet-redis/issues/401), but without changes to REFERENCE.md.
All credit goes to @kolaCZek

add replicaof parameter(v2)

---

REFERENCE.md
manifests/init.pp
manifests/preinstall.pp
types/redisurl.pp

Add param to pass to apt-key adv, `http_proxy` for an instance

Add param to pass to apt-key adv

---

manifests/params.pp
metadata.json
spec/classes/redis_sentinel_spec.rb

Drop EoL Debian 9 support

---

spec/spec_helper_acceptance.rb

Drop Puppet 6 CI leftovers

---

.fixtures.yml
spec/spec_helper_acceptance.rb

CI: Switch sysctl module to new namespace & cleanup .fixtures.yml

---

CHANGELOG.md
metadata.json

Release 9.3.0

---

REFERENCE.md
manifests/init.pp
manifests/instance.pp
spec/classes/redis_spec.rb
templates/redis.conf.epp

Allow requirepass to be set as a Sensitive string

Allow `requirepass` to be set as a Sensitive string

---

metadata.json

Drop support for EoL CentOS 8

---

.github/workflows/ci.yml
.msync.yml
.overcommit.yml
.rspec
.rspec_parallel
.sync.yml
Gemfile
spec/spec.opts

modulesync 8.0.1

---

.github/CONTRIBUTING.md
.github/labeler.yml
.github/release.yml
.github/workflows/ci.yml
.github/workflows/labeler.yml
.github/workflows/release.yml
.msync.yml
.pmtignore
.puppet-lint.rc
Gemfile
spec/spec_helper.rb

modulesync 9.3.0

---

CHANGELOG.md
metadata.json

Release 11.1.0

---

REFERENCE.md
manifests/sentinel.pp
spec/classes/redis_sentinel_spec.rb
templates/redis-sentinel.conf.erb

This PR adds the parameter to configure the Sentinel announced port

Add parameter sentinel_announce_port

---

REFERENCE.md
manifests/init.pp
manifests/instance.pp
manifests/sentinel.pp
spec/classes/redis_sentinel_spec.rb
spec/classes/redis_spec.rb
templates/redis-sentinel.conf.erb
templates/redis.conf.epp

Add support for tls-key-file-pass

---

.sync.yml
Gemfile
spec/functions/redis/get_spec.rb
spec/spec_helper.rb
spec/unit/redis_server_version_spec.rb

Ref: https://github.com/voxpupuli/plumbing/issues/78

refactor: change from mocha to rspec-mocks

---

metadata.json

allow systemd 9
